# Generated by Django 2.2 on 2019-09-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Остаток'),
        ),
    ]
